package config

const BOX_LEN = 32
const RECT_LINE_WIDTH = 1
const BOARD_WIDTH = 20
const BOARD_HEIGHT = 20
const GUBARDBAND = 100
const WINDOW_HEIGHT = (BOARD_HEIGHT-1)*BOX_LEN + GUBARDBAND
const WINDOW_WIDTH = (BOARD_WIDTH-1)*BOX_LEN + GUBARDBAND
const BOMB_COUNT = 200
