package config

const RECT_WIDTH = 20
const RECT_HEIGHT = 20
const RECT_LINE_WIDTH = 1
const BOARD_WIDTH = 30
const BOARD_HEIGHT = 30
const GUBARDBAND = 50
const WINDOW_HEIGHT = (BOARD_HEIGHT+1)*RECT_HEIGHT + GUBARDBAND
const WINDOW_WIDTH = (BOARD_WIDTH+1)*RECT_WIDTH + GUBARDBAND
